// <auto-generated />
using FlashCard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlashCard.Migrations
{
    [DbContext(typeof(FlashCardContext))]
    partial class FlashCardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FlashCard.Models.Kanji", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayKanji");

                    b.Property<string>("DisplayWord");

                    b.Property<string>("Kana");

                    b.Property<string>("PronounceKanji");

                    b.HasKey("CardId");

                    b.ToTable("Kanjis");
                });
#pragma warning restore 612, 618
        }
    }
}
